FROM gocd/gocd-agent-alpine-3.5:v17.4.0

ADD ssh/* /home/go/.ssh/
RUN chown -R go:go /home/go/.ssh/

RUN apk add --update \
    gcc \
    g++ \
    make \
    libffi-dev \
    openssl-dev \
    build-base \
  && rm -rf /var/cache/apk/*


